SELECT TOP (1000) [Row_ID]
      ,[Order_ID]
      ,[Order_Date]
      ,[Ship_Date]
      ,[Ship_Mode]
      ,[Customer_ID]
      ,[Customer_Name]
      ,[Segment]
      ,[Country_Region]
      ,[City]
      ,[State]
      ,[Postal_Code]
      ,[Region]
      ,[Product_ID]
      ,[Category]
      ,[Sub_Category]
      ,[Product_Name]
      ,[Sales]
      ,[Quantity]
      ,[Discount]
      ,[Profit]
  FROM [gfg_da].[dbo].[sales]
  exec sp_rename'[dbo].[[dbo]].sales]','sales'  -
  select * from [dbo].sales
 
 --------- group by and having--------
 SELECT DISTINCT (CATEGORY) FROM SALES

 SELECT
 COUNT(CATEGORY),
 SUM(SALES)
 FROM SALES

 SELECT 
 CATEGORY,
 SUM(SALES) AS TOTAL_SALES
 FROM SALES 
 GROUP BY CATEGORY

 SELECT
  SUM(SALES) AS TOTAL_SALES
 FROM SALES 
 GROUP BY CATEGORY

 -----------REGIONWISE TOTAL QUATITY SOLD , PROFIT MADE, OVERALL SALES'------------
 SELECT 
 REGION,
 SUM(QUANTITY) AS TOTAL_REGION_QUALITY,
SUM(PROFIT),
MAX(PROFIT),
MIN(PROFIT),
AVG(PROFIT),
COUNT(ORDER_ID)
FROM SALES 
GROUP BY REGION
-----------------------------------
--------EACH REGION EACH CATEGORY ----------
SELECT 
 REGION,
 CATEGORY,
 SUM(QUANTITY) AS TOTAL_REGION_QUALITY,
SUM(PROFIT),
MAX(PROFIT),
MIN(PROFIT),
AVG(PROFIT),
COUNT(ORDER_ID)
FROM SALES 
GROUP BY REGION,CATEGORY
ORDER BY REGION

---------GIVE ME YEAR WISE SALES AND YEAR WISE PROFITS----
SELECT 
YEAR(ORDER_DATE) AS YR,
SUM(SALES)
FROM SALES
GROUP BY YEAR(ORDER_DATE)
-------------------------
SELECT SUB_CATEGORY,
SUM(SALES)
FROM SALES
GROUP BY SUB_CATEGORY

SELECT SUB_CATEGORY,
SUM(SALES)
FROM SALES
GROUP BY SUB_CATEGORY
HAVING SUM(SALES)>65000 


-------HAVING (NEED AGGREGATE FUNCTION AND SHOULD BE USED AFTER GROUP BY FUNCTION)-----------
--------TOTAL SALES>65000 AND SHOULD NOT INCLUDE BLINDERS AND TABLES ---------
SELECT SUB_CATEGORY,
SUM(SALES)
FROM SALES 
WHERE SUB_CATEGORY NOT IN ('BLINDERS','TABLES')
GROUP BY SUB_CATEGORY 
HAVING SUM(SALES)>65000 
---------------------------------------------------
SELECT SUB_CATEGORY,
SUM(SALES)
FROM SALES 
GROUP BY SUB_CATEGORY 
HAVING SUM(SALES)>65000 AND SUB_CATEGORY NOT IN ('BLINDERS','TABLES')

SELECT 
REGION,
AVG(DISCOUNT) AS AVG_DISCOUNT
FROM SALES
GROUP BY REGION
HAVING AVG(DISCOUNT)> 0.15620
ORDER BY REGION

SELECT AVG(DISCOUNT) FROM SALES

SELECT TOP 3
REGION,
SUM(SALES) AS TOTAL_SALES 
FROM SALES 
GROUP BY REGION 
ORDER BY SUM (SALES) DESC

---------------------------------
SELECT 
SUB_CATEGORY,
ROW_NUMBER() OVER (



